// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiUrWj5Si3BkUfHLPaAAqkc4zArYgwZt0',
    appId: '1:749528386297:android:878f8bd28f5c56b3db7028',
    messagingSenderId: '749528386297',
    projectId: 'kusoed-app-sajin',
    storageBucket: 'kusoed-app-sajin.firebasestorage.app',
  );
}
